<?php

declare(strict_types=1);

/*
 * PQAPIV2Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PQAPIV2Lib\Tests;

class ClientFactory
{
    public static function create(HttpCallBackCatcher $httpCallback): \PQAPIV2Lib\PQAPIV2Client
    {
        $client = (new \PQAPIV2Lib\PQAPIV2Client(static::getConfigurationFromEnvironment()))
            ->withConfiguration(static::getTestConfiguration($httpCallback));
        return $client;
    }

    public static function getTestConfiguration(HttpCallBackCatcher $httpCallback): array
    {
        return ['httpCallback' => $httpCallback];
    }

    public static function getConfigurationFromEnvironment(): array
    {
        $config = [];
        $timeout = getenv('PQAPIV_2_LIB_TIMEOUT');
        $numberOfRetries = getenv('PQAPIV_2_LIB_NUMBER_OF_RETRIES');
        $maximumRetryWaitTime = getenv('PQAPIV_2_LIB_MAXIMUM_RETRY_WAIT_TIME');
        $environment = getenv('PQAPIV_2_LIB_ENVIRONMENT');

        if ($timeout !== false && \is_numeric($timeout)) {
            $config['timeout'] = intval($timeout);
        }

        if ($numberOfRetries !== false && \is_numeric($numberOfRetries)) {
            $config['numberOfRetries'] = intval($numberOfRetries);
        }

        if ($maximumRetryWaitTime !== false && \is_numeric($maximumRetryWaitTime)) {
            $config['maximumRetryWaitTime'] = intval($maximumRetryWaitTime);
        }

        if ($environment !== false) {
            $config['environment'] = $environment;
        }

        return $config;
    }
}
