<?php

declare(strict_types=1);

/*
 * PQAPIV2Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PQAPIV2Lib\Models;

/**
 * Classifies the address type (<i>Home</i>, <i>Business</i>, <i>Billing</i>, <i>Shipping</i>)
 */
class AddressTypesEnum
{
    public const RESIDENTIAL = 'RESIDENTIAL';

    public const BUSINESS = 'BUSINESS';

    public const MAILING = 'MAILING';
}
