<?php

declare(strict_types=1);

/*
 * PQAPIV2Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PQAPIV2Lib\Models;

/**
 * Classifies account field types
 */
class BankAccountFieldTypesEnum
{
    public const BANK_ACH_ABA = 'BANK_ACH_ABA';

    public const BANK_BBAN = 'BANK_BBAN';

    public const BANK_BRANCH_CODE = 'BANK_BRANCH_CODE';

    public const BANK_BSB_CODE = 'BANK_BSB_CODE';

    public const BANK_CITY = 'BANK_CITY';

    public const BANK_CLABE = 'BANK_CLABE';

    public const BANK_CODE = 'BANK_CODE';

    public const BANK_CURP = 'BANK_CURP';

    public const BANK_IBAN = 'BANK_IBAN';

    public const BANK_NAME = 'BANK_NAME';

    public const BANK_NON_SWIFT_BIC = 'BANK_NON_SWIFT_BIC';

    public const BANK_NUBAN = 'BANK_NUBAN';

    public const BANK_PHONE_NUMBER = 'BANK_PHONE_NUMBER';

    public const BANK_POSTAL_CODE = 'BANK_POSTAL_CODE';

    public const BANK_REGION = 'BANK_REGION';

    public const BANK_RFC = 'BANK_RFC';

    public const BANK_SORT_CODE = 'BANK_SORT_CODE';

    public const BANK_STREET_ADDRESS = 'BANK_STREET_ADDRESS';

    public const BANK_SWIFT_BIC = 'BANK_SWIFT_BIC';

    public const BANK_TRANSIT_CODE = 'BANK_TRANSIT_CODE';

    public const BENEFICIARY_ACCOUNT_NUMBER = 'BENEFICIARY_ACCOUNT_NUMBER';

    public const BENEFICIARY_PHONE_NUMBER = 'BENEFICIARY_PHONE_NUMBER';

    public const BENEFICIARY_TAX_ID = 'BENEFICIARY_TAX_ID';

    public const BENEFICIARY_NAME = 'BENEFICIARY_NAME';

    public const BANK_BRANCH_NAME = 'BANK_BRANCH_NAME';

    public const BANK_PURPOSE_OF_PAYMENT_CODE = 'BANK_PURPOSE_OF_PAYMENT_CODE';

    public const BANK_VALUE_ADD_TAX = 'BANK_VALUE_ADD_TAX';
}
