<?php

declare(strict_types=1);

/*
 * PQAPIV2Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PQAPIV2Lib\Models;

/**
 * Account ownership types
 */
class BankAccountOwnershipTypesEnum
{
    public const PERSONAL = 'PERSONAL';

    public const BUSINESS = 'BUSINESS';
}
