<?php

declare(strict_types=1);

/*
 * PQAPIV2Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PQAPIV2Lib\Models;

use stdClass;

/**
 * Classifies the format of the required information for a bank account
 */
class BankAccountRequirementFormat implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $example;

    /**
     * @var BankAccountRequirementFormatLegend[]|null
     */
    private $legend;

    /**
     * Returns Example.
     * Example of a requirement generated from the validator(s)
     */
    public function getExample(): ?string
    {
        return $this->example;
    }

    /**
     * Sets Example.
     * Example of a requirement generated from the validator(s)
     *
     * @maps example
     */
    public function setExample(?string $example): void
    {
        $this->example = $example;
    }

    /**
     * Returns Legend.
     *
     * @return BankAccountRequirementFormatLegend[]|null
     */
    public function getLegend(): ?array
    {
        return $this->legend;
    }

    /**
     * Sets Legend.
     *
     * @maps legend
     *
     * @param BankAccountRequirementFormatLegend[]|null $legend
     */
    public function setLegend(?array $legend): void
    {
        $this->legend = $legend;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->example)) {
            $json['example'] = $this->example;
        }
        if (isset($this->legend)) {
            $json['legend']  = $this->legend;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
