<?php

declare(strict_types=1);

/*
 * PQAPIV2Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PQAPIV2Lib\Models;

/**
 * Current verification status type of the bank account
 */
class BankAccountStatusTypesEnum
{
    public const DELETED = 'DELETED';

    public const ACTIVE = 'ACTIVE';

    public const PENDING_VERIFICATION = 'PENDING_VERIFICATION';
}
