<?php

declare(strict_types=1);

/*
 * PQAPIV2Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PQAPIV2Lib\Models;

/**
 * Financial purpose of the bank account (<i>Savings</i>, <i>Investment</i>)
 */
class BankAccountTypesEnum
{
    public const CHECKING = 'CHECKING';

    public const SAVINGS = 'SAVINGS';

    public const MONEY_MARKET = 'MONEY_MARKET';
}
