<?php

declare(strict_types=1);

/*
 * PQAPIV2Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PQAPIV2Lib\Models;

use stdClass;

class BusinessType implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $businessType;

    /**
     * Returns Business Type.
     * Type of business (<i>Corporation</i> or <i>Partnership</i>)
     */
    public function getBusinessType(): ?string
    {
        return $this->businessType;
    }

    /**
     * Sets Business Type.
     * Type of business (<i>Corporation</i> or <i>Partnership</i>)
     *
     * @maps businessType
     */
    public function setBusinessType(?string $businessType): void
    {
        $this->businessType = $businessType;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->businessType)) {
            $json['businessType'] = $this->businessType;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
