<?php

declare(strict_types=1);

/*
 * PQAPIV2Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PQAPIV2Lib\Models;

use stdClass;

/**
 * Physical address of the business and other information, such as <i>Operating Name</i>,
 * <i>Registration ID</i>, etc.
 */
class BusinessInformation implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $businessName;

    /**
     * @var string|null
     */
    private $businessOperatingName;

    /**
     * @var string|null
     */
    private $businessRegistrationId;

    /**
     * @var string|null
     */
    private $businessRegistrationRegion;

    /**
     * @var string|null
     */
    private $businessRegistrationCountry;

    /**
     * @var string|null
     */
    private $businessContactRole;

    /**
     * @var string|null
     */
    private $businessAddressLine1;

    /**
     * @var string|null
     */
    private $businessAddressLine2;

    /**
     * @var string|null
     */
    private $businessAddressLine3;

    /**
     * @var string|null
     */
    private $businessAddressLine4;

    /**
     * @var string|null
     */
    private $businessAddressLine5;

    /**
     * @var string|null
     */
    private $businessCity;

    /**
     * @var string|null
     */
    private $businessRegion;

    /**
     * @var string|null
     */
    private $businessCountry;

    /**
     * @var string|null
     */
    private $businessPostalCode;

    /**
     * @var string|null
     */
    private $businessPremiseNumber;

    /**
     * @var string|null
     */
    private $businessType;

    /**
     * Returns Business Name.
     * Legal name for the business
     */
    public function getBusinessName(): ?string
    {
        return $this->businessName;
    }

    /**
     * Sets Business Name.
     * Legal name for the business
     *
     * @maps businessName
     */
    public function setBusinessName(?string $businessName): void
    {
        $this->businessName = $businessName;
    }

    /**
     * Returns Business Operating Name.
     * Name under which the business operates
     */
    public function getBusinessOperatingName(): ?string
    {
        return $this->businessOperatingName;
    }

    /**
     * Sets Business Operating Name.
     * Name under which the business operates
     *
     * @maps businessOperatingName
     */
    public function setBusinessOperatingName(?string $businessOperatingName): void
    {
        $this->businessOperatingName = $businessOperatingName;
    }

    /**
     * Returns Business Registration Id.
     * Registration number or ID assigned by a government body
     */
    public function getBusinessRegistrationId(): ?string
    {
        return $this->businessRegistrationId;
    }

    /**
     * Sets Business Registration Id.
     * Registration number or ID assigned by a government body
     *
     * @maps businessRegistrationId
     */
    public function setBusinessRegistrationId(?string $businessRegistrationId): void
    {
        $this->businessRegistrationId = $businessRegistrationId;
    }

    /**
     * Returns Business Registration Region.
     * State, province, or territory where the business is registered
     */
    public function getBusinessRegistrationRegion(): ?string
    {
        return $this->businessRegistrationRegion;
    }

    /**
     * Sets Business Registration Region.
     * State, province, or territory where the business is registered
     *
     * @maps businessRegistrationRegion
     */
    public function setBusinessRegistrationRegion(?string $businessRegistrationRegion): void
    {
        $this->businessRegistrationRegion = $businessRegistrationRegion;
    }

    /**
     * Returns Business Registration Country.
     * Two-digit country code types
     */
    public function getBusinessRegistrationCountry(): ?string
    {
        return $this->businessRegistrationCountry;
    }

    /**
     * Sets Business Registration Country.
     * Two-digit country code types
     *
     * @maps businessRegistrationCountry
     */
    public function setBusinessRegistrationCountry(?string $businessRegistrationCountry): void
    {
        $this->businessRegistrationCountry = $businessRegistrationCountry;
    }

    /**
     * Returns Business Contact Role.
     * Role of the user within the business
     */
    public function getBusinessContactRole(): ?string
    {
        return $this->businessContactRole;
    }

    /**
     * Sets Business Contact Role.
     * Role of the user within the business
     *
     * @maps businessContactRole
     */
    public function setBusinessContactRole(?string $businessContactRole): void
    {
        $this->businessContactRole = $businessContactRole;
    }

    /**
     * Returns Business Address Line 1.
     * First line of the business address that specifies street number, street name, and building name
     */
    public function getBusinessAddressLine1(): ?string
    {
        return $this->businessAddressLine1;
    }

    /**
     * Sets Business Address Line 1.
     * First line of the business address that specifies street number, street name, and building name
     *
     * @maps businessAddressLine1
     */
    public function setBusinessAddressLine1(?string $businessAddressLine1): void
    {
        $this->businessAddressLine1 = $businessAddressLine1;
    }

    /**
     * Returns Business Address Line 2.
     * Second line of the business address that specifies the apartment, suite, or space number (or any
     * other designation not literally part of the physical address)
     */
    public function getBusinessAddressLine2(): ?string
    {
        return $this->businessAddressLine2;
    }

    /**
     * Sets Business Address Line 2.
     * Second line of the business address that specifies the apartment, suite, or space number (or any
     * other designation not literally part of the physical address)
     *
     * @maps businessAddressLine2
     */
    public function setBusinessAddressLine2(?string $businessAddressLine2): void
    {
        $this->businessAddressLine2 = $businessAddressLine2;
    }

    /**
     * Returns Business Address Line 3.
     * Third line of the business address that specifies the international or business addresses that do
     * not fit on businessAddressLine3
     */
    public function getBusinessAddressLine3(): ?string
    {
        return $this->businessAddressLine3;
    }

    /**
     * Sets Business Address Line 3.
     * Third line of the business address that specifies the international or business addresses that do
     * not fit on businessAddressLine3
     *
     * @maps businessAddressLine3
     */
    public function setBusinessAddressLine3(?string $businessAddressLine3): void
    {
        $this->businessAddressLine3 = $businessAddressLine3;
    }

    /**
     * Returns Business Address Line 4.
     * fourth line of the business address street address
     */
    public function getBusinessAddressLine4(): ?string
    {
        return $this->businessAddressLine4;
    }

    /**
     * Sets Business Address Line 4.
     * fourth line of the business address street address
     *
     * @maps businessAddressLine4
     */
    public function setBusinessAddressLine4(?string $businessAddressLine4): void
    {
        $this->businessAddressLine4 = $businessAddressLine4;
    }

    /**
     * Returns Business Address Line 5.
     * Fifth line of the business address street address
     */
    public function getBusinessAddressLine5(): ?string
    {
        return $this->businessAddressLine5;
    }

    /**
     * Sets Business Address Line 5.
     * Fifth line of the business address street address
     *
     * @maps businessAddressLine5
     */
    public function setBusinessAddressLine5(?string $businessAddressLine5): void
    {
        $this->businessAddressLine5 = $businessAddressLine5;
    }

    /**
     * Returns Business City.
     * City the business is registered
     */
    public function getBusinessCity(): ?string
    {
        return $this->businessCity;
    }

    /**
     * Sets Business City.
     * City the business is registered
     *
     * @maps businessCity
     */
    public function setBusinessCity(?string $businessCity): void
    {
        $this->businessCity = $businessCity;
    }

    /**
     * Returns Business Region.
     * State, province, or region the business is registered
     */
    public function getBusinessRegion(): ?string
    {
        return $this->businessRegion;
    }

    /**
     * Sets Business Region.
     * State, province, or region the business is registered
     *
     * @maps businessRegion
     */
    public function setBusinessRegion(?string $businessRegion): void
    {
        $this->businessRegion = $businessRegion;
    }

    /**
     * Returns Business Country.
     * Two-digit country code types
     */
    public function getBusinessCountry(): ?string
    {
        return $this->businessCountry;
    }

    /**
     * Sets Business Country.
     * Two-digit country code types
     *
     * @maps businessCountry
     */
    public function setBusinessCountry(?string $businessCountry): void
    {
        $this->businessCountry = $businessCountry;
    }

    /**
     * Returns Business Postal Code.
     * Postal code for the business address
     */
    public function getBusinessPostalCode(): ?string
    {
        return $this->businessPostalCode;
    }

    /**
     * Sets Business Postal Code.
     * Postal code for the business address
     *
     * @maps businessPostalCode
     */
    public function setBusinessPostalCode(?string $businessPostalCode): void
    {
        $this->businessPostalCode = $businessPostalCode;
    }

    /**
     * Returns Business Premise Number.
     * House number for the business address
     */
    public function getBusinessPremiseNumber(): ?string
    {
        return $this->businessPremiseNumber;
    }

    /**
     * Sets Business Premise Number.
     * House number for the business address
     *
     * @maps businessPremiseNumber
     */
    public function setBusinessPremiseNumber(?string $businessPremiseNumber): void
    {
        $this->businessPremiseNumber = $businessPremiseNumber;
    }

    /**
     * Returns Business Type.
     * Type of business (<i>Corporation</i> or <i>Partnership</i>)
     */
    public function getBusinessType(): ?string
    {
        return $this->businessType;
    }

    /**
     * Sets Business Type.
     * Type of business (<i>Corporation</i> or <i>Partnership</i>)
     *
     * @maps businessType
     */
    public function setBusinessType(?string $businessType): void
    {
        $this->businessType = $businessType;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->businessName)) {
            $json['businessName']                = $this->businessName;
        }
        if (isset($this->businessOperatingName)) {
            $json['businessOperatingName']       = $this->businessOperatingName;
        }
        if (isset($this->businessRegistrationId)) {
            $json['businessRegistrationId']      = $this->businessRegistrationId;
        }
        if (isset($this->businessRegistrationRegion)) {
            $json['businessRegistrationRegion']  = $this->businessRegistrationRegion;
        }
        if (isset($this->businessRegistrationCountry)) {
            $json['businessRegistrationCountry'] = $this->businessRegistrationCountry;
        }
        if (isset($this->businessContactRole)) {
            $json['businessContactRole']         = $this->businessContactRole;
        }
        if (isset($this->businessAddressLine1)) {
            $json['businessAddressLine1']        = $this->businessAddressLine1;
        }
        if (isset($this->businessAddressLine2)) {
            $json['businessAddressLine2']        = $this->businessAddressLine2;
        }
        if (isset($this->businessAddressLine3)) {
            $json['businessAddressLine3']        = $this->businessAddressLine3;
        }
        if (isset($this->businessAddressLine4)) {
            $json['businessAddressLine4']        = $this->businessAddressLine4;
        }
        if (isset($this->businessAddressLine5)) {
            $json['businessAddressLine5']        = $this->businessAddressLine5;
        }
        if (isset($this->businessCity)) {
            $json['businessCity']                = $this->businessCity;
        }
        if (isset($this->businessRegion)) {
            $json['businessRegion']              = $this->businessRegion;
        }
        if (isset($this->businessCountry)) {
            $json['businessCountry']             = $this->businessCountry;
        }
        if (isset($this->businessPostalCode)) {
            $json['businessPostalCode']          = $this->businessPostalCode;
        }
        if (isset($this->businessPremiseNumber)) {
            $json['businessPremiseNumber']       = $this->businessPremiseNumber;
        }
        if (isset($this->businessType)) {
            $json['businessType']                = $this->businessType;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
