<?php

declare(strict_types=1);

/*
 * PQAPIV2Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PQAPIV2Lib\Models;

/**
 * Type of business (<i>Corporation</i> or <i>Partnership</i>)
 */
class BusinessTypesEnum
{
    public const CORPORATION = 'CORPORATION';

    public const PARTNERSHIP_DBA = 'PARTNERSHIP_DBA';
}
