<?php

declare(strict_types=1);

/*
 * PQAPIV2Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PQAPIV2Lib\Models;

use stdClass;

/**
 * Major credit card network
 */
class CardNetwork implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $cardNetwork;

    /**
     * Returns Card Network.
     * Major credit card network types
     */
    public function getCardNetwork(): ?string
    {
        return $this->cardNetwork;
    }

    /**
     * Sets Card Network.
     * Major credit card network types
     *
     * @maps cardNetwork
     */
    public function setCardNetwork(?string $cardNetwork): void
    {
        $this->cardNetwork = $cardNetwork;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->cardNetwork)) {
            $json['cardNetwork'] = $this->cardNetwork;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
