<?php

declare(strict_types=1);

/*
 * PQAPIV2Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PQAPIV2Lib\Models;

/**
 * Major credit card network types
 */
class CardNetworkTypesEnum
{
    public const VISA = 'VISA';

    public const MASTER_CARD = 'MASTER_CARD';
}
