<?php

declare(strict_types=1);

/*
 * PQAPIV2Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PQAPIV2Lib\Models;

use stdClass;

/**
 * Type of personalization for the prepaid card
 */
class CardPersonalizationType implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $cardPersonalization;

    /**
     * Returns Card Personalization.
     * Specifies a card is <i>Personalized</i> or <i>Non-personalized</i> (i.e., issued to Preferred
     * Customer)
     */
    public function getCardPersonalization(): ?string
    {
        return $this->cardPersonalization;
    }

    /**
     * Sets Card Personalization.
     * Specifies a card is <i>Personalized</i> or <i>Non-personalized</i> (i.e., issued to Preferred
     * Customer)
     *
     * @maps cardPersonalization
     */
    public function setCardPersonalization(?string $cardPersonalization): void
    {
        $this->cardPersonalization = $cardPersonalization;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->cardPersonalization)) {
            $json['cardPersonalization'] = $this->cardPersonalization;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
