<?php

declare(strict_types=1);

/*
 * PQAPIV2Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PQAPIV2Lib\Models;

use stdClass;

/**
 * Unique value provided by the client for the transfer, utilized for reference and deduplication.
 */
class ClientTransferId implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $clientTransferId;

    /**
     * Returns Client Transfer Id.
     * Unique value provided by the client for the transfer.
     */
    public function getClientTransferId(): ?string
    {
        return $this->clientTransferId;
    }

    /**
     * Sets Client Transfer Id.
     * Unique value provided by the client for the transfer.
     *
     * @maps clientTransferId
     */
    public function setClientTransferId(?string $clientTransferId): void
    {
        $this->clientTransferId = $clientTransferId;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->clientTransferId)) {
            $json['clientTransferId'] = $this->clientTransferId;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
