<?php

declare(strict_types=1);

/*
 * PQAPIV2Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PQAPIV2Lib\Models;

/**
 * Currency code type for the object
 */
class CurrencyTypesEnum
{
    public const USD = 'USD';

    public const CAD = 'CAD';

    public const MXN = 'MXN';

    public const AUD = 'AUD';

    public const HKD = 'HKD';

    public const NZD = 'NZD';

    public const EUR = 'EUR';

    public const GBP = 'GBP';
}
