<?php

declare(strict_types=1);

/*
 * PQAPIV2Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PQAPIV2Lib\Models;

use PQAPIV2Lib\Utils\DateTimeHelper;
use stdClass;

/**
 * Date and time the object will expire
 */
class Expiration implements \JsonSerializable
{
    /**
     * @var \DateTime|null
     */
    private $expires;

    /**
     * Returns Expires.
     * Quote expiration, ISO-8601 format, UTC by default unless overridden.
     */
    public function getExpires(): ?\DateTime
    {
        return $this->expires;
    }

    /**
     * Sets Expires.
     * Quote expiration, ISO-8601 format, UTC by default unless overridden.
     *
     * @maps expires
     * @factory \PQAPIV2Lib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setExpires(?\DateTime $expires): void
    {
        $this->expires = $expires;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->expires)) {
            $json['expires'] = DateTimeHelper::toRfc3339DateTime($this->expires);
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
