<?php

declare(strict_types=1);

/*
 * PQAPIV2Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PQAPIV2Lib\Models;

/**
 * Gender as a user identifies
 */
class GenderTypesEnum
{
    public const MALE = 'MALE';

    public const FEMALE = 'FEMALE';

    public const NOT_SPECIFIED = 'NOT_SPECIFIED';
}
