<?php

declare(strict_types=1);

/*
 * PQAPIV2Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PQAPIV2Lib\Models;

use stdClass;

/**
 * Indicates the HATEOS relationship between the target and current resources.
 */
class HaetosRelationship implements \JsonSerializable
{
    /**
     * @var string
     */
    private $rel;

    /**
     * @param string $rel
     */
    public function __construct(string $rel)
    {
        $this->rel = $rel;
    }

    /**
     * Returns Rel.
     * Indicates the relationship between the target and current resources.
     */
    public function getRel(): string
    {
        return $this->rel;
    }

    /**
     * Sets Rel.
     * Indicates the relationship between the target and current resources.
     *
     * @required
     * @maps rel
     */
    public function setRel(string $rel): void
    {
        $this->rel = $rel;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['rel'] = $this->rel;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
