<?php

declare(strict_types=1);

/*
 * PQAPIV2Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PQAPIV2Lib\Models;

use stdClass;

/**
 * Type of verification used for performing an identity check
 */
class IdentityVerificationCheckType implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $idvCheckType;

    /**
     * Returns Idv Check Type.
     * Types of verification used for performing identity checks (<i>documentary</i>, <i>non-
     * documentary</i>, <i>OFAC</i>, etc.)
     */
    public function getIdvCheckType(): ?string
    {
        return $this->idvCheckType;
    }

    /**
     * Sets Idv Check Type.
     * Types of verification used for performing identity checks (<i>documentary</i>, <i>non-
     * documentary</i>, <i>OFAC</i>, etc.)
     *
     * @maps idvCheckType
     */
    public function setIdvCheckType(?string $idvCheckType): void
    {
        $this->idvCheckType = $idvCheckType;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->idvCheckType)) {
            $json['idvCheckType'] = $this->idvCheckType;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
