<?php

declare(strict_types=1);

/*
 * PQAPIV2Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PQAPIV2Lib\Models;

/**
 * If used by a provider, sub-results that give additional insight into the results, including whether
 * they result was <i>Soft</i> or <i>Hard</i>. <i>Soft</i> results may have additional recourse that
 * can be leveraged to validate a user’s identity.
 */
class IdentityVerificationResultSubTypesEnum
{
    public const HARD = 'HARD';

    public const SOFT = 'SOFT';
}
