<?php

declare(strict_types=1);

/*
 * PQAPIV2Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PQAPIV2Lib\Models;

/**
 * Types of verification used for performing identity checks (<i>documentary</i>, <i>non-
 * documentary</i>, <i>OFAC</i>, etc.)
 */
class IdentityVerificationCheckTypesEnum
{
    public const DOCUMENTARY = 'DOCUMENTARY';

    public const NON_DOCUMENTARY = 'NON_DOCUMENTARY';

    public const OFAC = 'OFAC';
}
