<?php

declare(strict_types=1);

/*
 * PQAPIV2Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PQAPIV2Lib\Models;

/**
 * Provider types of verification that can be used for performing identity checks
 */
class IdentityVerificationProviderTypesEnum
{
    public const W2 = 'W2';

    public const IDOLOGY = 'IDOLOGY';

    public const BANK = 'BANK';

    public const EQUIFAX = 'EQUIFAX';

    public const OFAC = 'OFAC';

    public const LEXUS_NEXUS = 'LEXUS_NEXUS';
}
