<?php

declare(strict_types=1);

/*
 * PQAPIV2Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PQAPIV2Lib\Models;

/**
 * Type of occupation for the user
 */
class OccupationTypesEnum
{
    public const INDEPENDENT_BUSINESS_OWNER = 'INDEPENDENT_BUSINESS_OWNER';

    public const SCIENCE = 'SCIENCE';

    public const TECHNOLOGY = 'TECHNOLOGY';

    public const ENGINEERING = 'ENGINEERING';

    public const MATH = 'MATH';

    public const HEALTHCARE = 'HEALTHCARE';

    public const SOCIAL_SERVICES = 'SOCIAL_SERVICES';

    public const MEDIA = 'MEDIA';

    public const FINANCE = 'FINANCE';

    public const GOVERNMENT = 'GOVERNMENT';

    public const MANUFACTURING = 'MANUFACTURING';

    public const LAW = 'LAW';

    public const HOSPITALITY_AND_TOURISM = 'HOSPITALITY_AND_TOURISM';

    public const ARTS = 'ARTS';

    public const DESIGN = 'DESIGN';

    public const OFFICE_AND_ADMIN_SUPPORT = 'OFFICE_AND_ADMIN_SUPPORT';

    public const EDUCATION = 'EDUCATION';
}
