<?php

declare(strict_types=1);

/*
 * PQAPIV2Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PQAPIV2Lib\Models;

/**
 * Used to identify the purpose of a payment and impacts reporting and calculated taxable earnings (if
 * utilizing tax services)
 */
class PaymentPurposeTypesEnum
{
    public const OTHER = 'OTHER';

    public const TAXABLE = 'TAXABLE';

    public const INCOME = 'INCOME';

    public const BONUS = 'BONUS';

    public const EXPENSE = 'EXPENSE';

    public const NON_TAXABLE = 'NON_TAXABLE';
}
