<?php

declare(strict_types=1);

/*
 * PQAPIV2Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PQAPIV2Lib\Models;

/**
 * Specifies a card is <i>Personalized</i> or <i>Non-personalized</i> (i.e., issued to Preferred
 * Customer)
 */
class PrepaidCardPersonalizationTypesEnum
{
    public const PERSONALIZED = 'PERSONALIZED';

    public const NON_PERSONALIZED = 'NON_PERSONALIZED';
}
