<?php

declare(strict_types=1);

/*
 * PQAPIV2Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PQAPIV2Lib\Models;

use stdClass;

class PrepaidCardReplacementReason implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $cardReplacementReason;

    /**
     * Returns Card Replacement Reason.
     * Reason for card replacement. In certain programs, the replacement reason code impacts replacement
     * cost and responsibility.
     */
    public function getCardReplacementReason(): ?string
    {
        return $this->cardReplacementReason;
    }

    /**
     * Sets Card Replacement Reason.
     * Reason for card replacement. In certain programs, the replacement reason code impacts replacement
     * cost and responsibility.
     *
     * @maps cardReplacementReason
     */
    public function setCardReplacementReason(?string $cardReplacementReason): void
    {
        $this->cardReplacementReason = $cardReplacementReason;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->cardReplacementReason)) {
            $json['cardReplacementReason'] = $this->cardReplacementReason;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
