<?php

declare(strict_types=1);

/*
 * PQAPIV2Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PQAPIV2Lib\Models;

/**
 * Reason for card replacement. In certain programs, the replacement reason code impacts replacement
 * cost and responsibility.
 */
class PrepaidCardReplacementReasonTypesEnum
{
    public const LOST = 'LOST';

    public const STOLEN = 'STOLEN';

    public const DAMAGED = 'DAMAGED';

    public const COMPROMISED = 'COMPROMISED';

    public const EXPIRED = 'EXPIRED';
}
