<?php

declare(strict_types=1);

/*
 * PQAPIV2Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PQAPIV2Lib\Models;

use stdClass;

/**
 * Base class applied to the prepaid card
 */
class PrepaidCardBase implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $cardPackage;

    /**
     * @var string
     */
    private $programToken;

    /**
     * @param string $programToken
     */
    public function __construct(string $programToken)
    {
        $this->programToken = $programToken;
    }

    /**
     * Returns Card Package.
     * Package for the card being displayed (<i>Virtual<,i>) or <i>Produced (physical)</i>
     */
    public function getCardPackage(): ?string
    {
        return $this->cardPackage;
    }

    /**
     * Sets Card Package.
     * Package for the card being displayed (<i>Virtual<,i>) or <i>Produced (physical)</i>
     *
     * @maps cardPackage
     */
    public function setCardPackage(?string $cardPackage): void
    {
        $this->cardPackage = $cardPackage;
    }

    /**
     * Returns Program Token.
     * Token representing a program
     */
    public function getProgramToken(): string
    {
        return $this->programToken;
    }

    /**
     * Sets Program Token.
     * Token representing a program
     *
     * @required
     * @maps programToken
     */
    public function setProgramToken(string $programToken): void
    {
        $this->programToken = $programToken;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->cardPackage)) {
            $json['cardPackage'] = $this->cardPackage;
        }
        $json['programToken']    = $this->programToken;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
