<?php

declare(strict_types=1);

/*
 * PQAPIV2Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PQAPIV2Lib\Models;

use stdClass;

/**
 * Package for the card being displayed (<i>Virtual<,i>) or <i>Produced (physical)</i>, including
 * artwork, packaging, and delivery method
 */
class PrepaidCardPackage implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $cardPackage;

    /**
     * Returns Card Package.
     * Package for the card being displayed (<i>Virtual<,i>) or <i>Produced (physical)</i>
     */
    public function getCardPackage(): ?string
    {
        return $this->cardPackage;
    }

    /**
     * Sets Card Package.
     * Package for the card being displayed (<i>Virtual<,i>) or <i>Produced (physical)</i>
     *
     * @maps cardPackage
     */
    public function setCardPackage(?string $cardPackage): void
    {
        $this->cardPackage = $cardPackage;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->cardPackage)) {
            $json['cardPackage'] = $this->cardPackage;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
