<?php

declare(strict_types=1);

/*
 * PQAPIV2Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PQAPIV2Lib\Models;

class SideEnum
{
    public const FRONT = 'FRONT';

    public const BACK = 'BACK';
}
