<?php

declare(strict_types=1);

/*
 * PQAPIV2Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PQAPIV2Lib\Models;

/**
 * Current status of the prepaid card
 */
class StatusEnum
{
    public const QUEUED = 'QUEUED';

    public const LOST_STOLEN_DAMAGED = 'LOST_STOLEN_DAMAGED';

    public const ACTIVATED = 'ACTIVATED';

    public const PENDING_ACTIVATION = 'PENDING_ACTIVATION';

    public const SUSPENDED = 'SUSPENDED';

    public const COMPLIANCE_HOLD = 'COMPLIANCE_HOLD';

    public const KYC_HOLD = 'KYC_HOLD';

    public const LOCKED = 'LOCKED';
}
