<?php

declare(strict_types=1);

/*
 * PQAPIV2Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PQAPIV2Lib\Models;

/**
 * Tax resident status type of a country
 */
class TaxResidentStatusTypesEnum
{
    public const YES = 'YES';

    public const NO = 'NO';

    public const PREFER_NOT_TO_ANSWER = 'PREFER_NOT_TO_ANSWER';
}
