<?php

declare(strict_types=1);

/*
 * PQAPIV2Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PQAPIV2Lib\Models;

use stdClass;

class TaxResidentStatus implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $taxResidentStatus;

    /**
     * Returns Tax Resident Status.
     * Tax resident status type of a country
     */
    public function getTaxResidentStatus(): ?string
    {
        return $this->taxResidentStatus;
    }

    /**
     * Sets Tax Resident Status.
     * Tax resident status type of a country
     *
     * @maps taxResidentStatus
     */
    public function setTaxResidentStatus(?string $taxResidentStatus): void
    {
        $this->taxResidentStatus = $taxResidentStatus;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->taxResidentStatus)) {
            $json['taxResidentStatus'] = $this->taxResidentStatus;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
