<?php

declare(strict_types=1);

/*
 * PQAPIV2Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PQAPIV2Lib\Models;

/**
 * Types of resources represented by a token
 */
class TokenTypesEnum
{
    public const BANK_ACCOUNT = 'BANK_ACCOUNT';

    public const TRANSFER = 'TRANSFER';

    public const PAYMENT = 'PAYMENT';

    public const SPEND_BACK = 'SPEND_BACK';

    public const PREPAID_CARD = 'PREPAID_CARD';

    public const USER = 'USER';

    public const DOCUMENT = 'DOCUMENT';

    public const ACCOUNT = 'ACCOUNT';
}
