<?php

declare(strict_types=1);

/*
 * PQAPIV2Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PQAPIV2Lib\Models;

/**
 * Current status of a transfer
 */
class TransferStatusTypesEnum
{
    public const QUOTED = 'QUOTED';

    public const PENDING = 'PENDING';

    public const SCHEDULED = 'SCHEDULED';

    public const COMPLETED = 'COMPLETED';

    public const CANCELLED = 'CANCELLED';

    public const RETURNED = 'RETURNED';

    public const FAILED = 'FAILED';

    public const EXPIRED = 'EXPIRED';

    public const VERIFICATION_HOLD = 'VERIFICATION_HOLD';
}
