<?php

declare(strict_types=1);

/*
 * PQAPIV2Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PQAPIV2Lib\Models;

use stdClass;

/**
 * User's profile type
 */
class UserType implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $userType;

    /**
     * Returns User Type.
     * Account holder's profile type
     */
    public function getUserType(): ?string
    {
        return $this->userType;
    }

    /**
     * Sets User Type.
     * Account holder's profile type
     *
     * @maps userType
     */
    public function setUserType(?string $userType): void
    {
        $this->userType = $userType;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->userType)) {
            $json['userType'] = $this->userType;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
