<?php

declare(strict_types=1);

/*
 * PQAPIV2Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PQAPIV2Lib\Models;

use stdClass;

/**
 * User's employer identifier, generally used for tax purposes.
 */
class UserEmployerId implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $employerId;

    /**
     * Returns Employer Id.
     * User's employer identifier
     */
    public function getEmployerId(): ?string
    {
        return $this->employerId;
    }

    /**
     * Sets Employer Id.
     * User's employer identifier
     *
     * @maps employerId
     */
    public function setEmployerId(?string $employerId): void
    {
        $this->employerId = $employerId;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->employerId)) {
            $json['employerId'] = $this->employerId;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
