<?php

declare(strict_types=1);

/*
 * PQAPIV2Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PQAPIV2Lib\Models;

/**
 * Account holder's profile type
 */
class UserTypesEnum
{
    public const INDIVIDUAL = 'INDIVIDUAL';

    public const BUSINESS = 'BUSINESS';
}
