<?php

declare(strict_types=1);

/*
 * PQAPIV2Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PQAPIV2Lib\Models;

class ValidatorTypesEnum
{
    public const REGEX = 'REGEX';

    public const LENGTH = 'LENGTH';
}
