<?php

declare(strict_types=1);

/*
 * PQAPIV2Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PQAPIV2Lib\Models;

use stdClass;

/**
 * Webhook Subscription response
 */
class WebhookSubscriptionResponse implements \JsonSerializable
{
    /**
     * @var HaetosParams[]|null
     */
    private $links;

    /**
     * @var string|null
     */
    private $url;

    /**
     * @var string|null
     */
    private $mNamespace;

    /**
     * @var string|null
     */
    private $token;

    /**
     * @var string|null
     */
    private $created;

    /**
     * @var string|null
     */
    private $lastUpdated;

    /**
     * Returns Links.
     *
     * @return HaetosParams[]|null
     */
    public function getLinks(): ?array
    {
        return $this->links;
    }

    /**
     * Sets Links.
     *
     * @maps links
     *
     * @param HaetosParams[]|null $links
     */
    public function setLinks(?array $links): void
    {
        $this->links = $links;
    }

    /**
     * Returns Url.
     */
    public function getUrl(): ?string
    {
        return $this->url;
    }

    /**
     * Sets Url.
     *
     * @maps url
     */
    public function setUrl(?string $url): void
    {
        $this->url = $url;
    }

    /**
     * Returns M Namespace.
     * Namespace used to identify and refer to the object
     */
    public function getMNamespace(): ?string
    {
        return $this->mNamespace;
    }

    /**
     * Sets M Namespace.
     * Namespace used to identify and refer to the object
     *
     * @maps namespace
     */
    public function setMNamespace(?string $mNamespace): void
    {
        $this->mNamespace = $mNamespace;
    }

    /**
     * Returns Token.
     * Token for the webhook subscription
     */
    public function getToken(): ?string
    {
        return $this->token;
    }

    /**
     * Sets Token.
     * Token for the webhook subscription
     *
     * @maps token
     */
    public function setToken(?string $token): void
    {
        $this->token = $token;
    }

    /**
     * Returns Created.
     * Time stamp for the date the webhook subscription was created
     */
    public function getCreated(): ?string
    {
        return $this->created;
    }

    /**
     * Sets Created.
     * Time stamp for the date the webhook subscription was created
     *
     * @maps created
     */
    public function setCreated(?string $created): void
    {
        $this->created = $created;
    }

    /**
     * Returns Last Updated.
     * Time stamp for the date the webhook subscription was updated
     */
    public function getLastUpdated(): ?string
    {
        return $this->lastUpdated;
    }

    /**
     * Sets Last Updated.
     * Time stamp for the date the webhook subscription was updated
     *
     * @maps lastUpdated
     */
    public function setLastUpdated(?string $lastUpdated): void
    {
        $this->lastUpdated = $lastUpdated;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->links)) {
            $json['links']       = $this->links;
        }
        if (isset($this->url)) {
            $json['url']         = $this->url;
        }
        if (isset($this->mNamespace)) {
            $json['namespace']   = $this->mNamespace;
        }
        if (isset($this->token)) {
            $json['token']       = $this->token;
        }
        if (isset($this->created)) {
            $json['created']     = $this->created;
        }
        if (isset($this->lastUpdated)) {
            $json['lastUpdated'] = $this->lastUpdated;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
